using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.U2D.Sprites;
using UnityEngine;

namespace Feeder
{
    /// <summary>
    /// Renames sprite sub-assets inside Multiple/Polygon-mode textures through the official
    /// ISpriteEditorDataProvider API. A sprite in a Multiple-mode texture is generated by the
    /// TextureImporter, so AssetDatabase.RenameAsset cannot touch it; only this path keeps the
    /// name consistent across internalIDToNameTable, spriteSheet.sprites[].name and nameFileIdTable.
    ///
    /// The sprite's fileID (internalID / spriteID) is never changed — only the name — so every
    /// guid+fileID reference in prefabs/ScriptableObjects stays intact.
    /// </summary>
    public static class FSpriteRenameUtils
    {
        public static bool IsMultipleModeTexture(string assetPath)
        {
            var importer = AssetImporter.GetAtPath(assetPath) as TextureImporter;
            return importer != null &&
                   (importer.spriteImportMode == SpriteImportMode.Multiple ||
                    importer.spriteImportMode == SpriteImportMode.Polygon);
        }

        /// <summary>
        /// Renames one or more sprites inside a single Multiple/Polygon-mode texture.
        /// Renames are (oldName -> newName) pairs; unknown, empty or colliding names are skipped with a warning.
        /// Returns the number of sprites actually renamed.
        /// </summary>
        public static int RenameSprites(string texturePath, IEnumerable<(string oldName, string newName)> renames, bool saveAndReimport = true)
        {
            var importer = AssetImporter.GetAtPath(texturePath) as TextureImporter;
            if (importer == null)
            {
                Debug.LogWarning($"[FSpriteRename] Not a texture: {texturePath}");
                return 0;
            }
            if (importer.spriteImportMode != SpriteImportMode.Multiple &&
                importer.spriteImportMode != SpriteImportMode.Polygon)
            {
                Debug.LogWarning($"[FSpriteRename] Texture not in Multiple/Polygon mode: {texturePath}");
                return 0;
            }

            var factory = new SpriteDataProviderFactories();
            factory.Init();
            var provider = factory.GetSpriteEditorDataProviderFromObject(importer);
            if (provider == null)
            {
                Debug.LogWarning($"[FSpriteRename] No sprite data provider for: {texturePath}");
                return 0;
            }
            provider.InitSpriteEditorDataProvider();

            var rects = provider.GetSpriteRects();
            var nameFileId = provider.GetDataProvider<ISpriteNameFileIdDataProvider>();
            var pairs = nameFileId.GetNameFileIdPairs().ToList();

            // Track current names so we can reject collisions (nameFileIdTable keys must stay unique).
            var currentNames = new HashSet<string>(rects.Select(r => r.name));

            int renamed = 0;
            foreach (var (oldName, newName) in renames)
            {
                if (string.IsNullOrEmpty(newName) || oldName == newName)
                    continue;

                var rect = rects.FirstOrDefault(r => r.name == oldName);
                if (rect == null)
                {
                    Debug.LogWarning($"[FSpriteRename] Sprite '{oldName}' not found in {texturePath}");
                    continue;
                }
                if (currentNames.Contains(newName))
                {
                    Debug.LogWarning($"[FSpriteRename] Skipped '{oldName}' -> '{newName}': name already used in {texturePath}");
                    continue;
                }

                rect.name = newName;

                // Keep the existing fileId for this name so guid+fileID references stay intact.
                for (int i = 0; i < pairs.Count; i++)
                {
                    if (pairs[i].name == oldName)
                        pairs[i] = new SpriteNameFileIdPair(newName, pairs[i].GetFileGUID());
                }

                currentNames.Remove(oldName);
                currentNames.Add(newName);
                renamed++;
                Debug.Log($"[FSpriteRename] {oldName} -> {newName}  ({texturePath})");
            }

            if (renamed == 0)
                return 0;

            provider.SetSpriteRects(rects);
            nameFileId.SetNameFileIdPairs(pairs);
            provider.Apply();            // must come before SaveAndReimport
            if (saveAndReimport)
                importer.SaveAndReimport();
            return renamed;
        }

        /// <summary>
        /// For each Multiple-mode texture that contains exactly one sprite, renames that sprite to the
        /// texture file name. Textures with a different sprite count (or not in Multiple mode) are skipped.
        /// </summary>
        public static int SyncSpriteNamesToFileName(IEnumerable<string> texturePaths)
        {
            int total = 0;
            AssetDatabase.StartAssetEditing();
            try
            {
                foreach (var path in texturePaths)
                {
                    if (!IsMultipleModeTexture(path))
                        continue;

                    var sprites = AssetDatabase.LoadAllAssetsAtPath(path).OfType<Sprite>().ToArray();
                    if (sprites.Length != 1)
                    {
                        Debug.LogWarning($"[FSpriteRename] Skipped (expected exactly 1 sprite, found {sprites.Length}): {path}");
                        continue;
                    }

                    var fileName = Path.GetFileNameWithoutExtension(path);
                    total += RenameSprites(path, new[] { (sprites[0].name, fileName) }, saveAndReimport: true);
                }
            }
            finally
            {
                AssetDatabase.StopAssetEditing();
            }
            return total;
        }
    }
}
